import { boolean, integer, pgTable, text, timestamp } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').defaultNow(), updatedAt: timestamp('updatedAt').defaultNow() })
export const brainDump = pgTable('brain_dump', { id: text('id').primaryKey(), userId: text('userId').notNull(), content: text('content').notNull().default(''), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const subject = pgTable('subjects', { id: text('id').primaryKey(), userId: text('user_id').notNull(), name: text('name').notNull(), color: text('color').notNull().default('lavender'), icon: text('icon').notNull().default('book-open'), createdAt: timestamp('created_at').notNull().defaultNow() })
export const notes = pgTable('notes', { id: text('id').primaryKey(), userId: text('user_id').notNull(), subjectId: text('subject_id').notNull(), customTitle: text('custom_title').notNull(), originalFilename: text('original_filename').notNull(), fileUrl: text('file_url').notNull(), fileSize: integer('file_size').notNull(), uploadedAt: timestamp('uploaded_at').notNull().defaultNow(), isImportant: boolean('is_important').notNull().default(false) })
export const focusSessions = pgTable('focus_sessions', { id: text('id').primaryKey(), userId: text('user_id').notNull(), taskId: text('task_id'), durationMinutes: integer('duration_minutes').notNull(), completedAt: timestamp('completed_at').notNull().defaultNow() })
export const syllabusTopics = pgTable('syllabus_topics', { id: text('id').primaryKey(), userId: text('user_id').notNull(), subjectId: text('subject_id').notNull(), name: text('name').notNull(), covered: boolean('covered').notNull().default(false), createdAt: timestamp('created_at').notNull().defaultNow() })
export const task = pgTable('task', { id: text('id').primaryKey(), userId: text('userId').notNull(), title: text('title').notNull(), category: text('category').notNull().default('Today'), priority: text('priority').notNull().default('Medium'), time: text('time').notNull().default('Today'), dueDate: timestamp('due_date'), done: boolean('done').notNull().default(false), subjectId: text('subject_id'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
