'use server'

import { and, eq } from 'drizzle-orm'
import { headers } from 'next/headers'
import { auth } from '@/lib/auth'
import { db } from '@/lib/db'
import { subject, timetableEntries, userSettings } from '@/lib/db/schema'

async function getUserId() { const session = await auth.api.getSession({ headers: await headers() }); if (!session?.user) throw new Error('Unauthorized'); return session.user.id }
export async function getTimetableData() { const userId = await getUserId(); const [entries, settings] = await Promise.all([db.select().from(timetableEntries).where(eq(timetableEntries.userId, userId)), db.select().from(userSettings).where(eq(userSettings.userId, userId)).limit(1)]); return { entries, labGroup: settings[0]?.labGroup ?? null } }
export async function saveLabGroup(labGroup: 'G1' | 'G2' | null) { const userId = await getUserId(); const existing = await db.select().from(userSettings).where(eq(userSettings.userId, userId)).limit(1); if (existing[0]) return (await db.update(userSettings).set({ labGroup }).where(eq(userSettings.userId, userId)).returning())[0]; return (await db.insert(userSettings).values({ userId, labGroup }).returning())[0] }
export type TimetableInput = { dayOfWeek:number; startTime:string; endTime:string; title:string; slotCode?:string|null; kind:'lecture'|'lab'|'tutorial'|'break'|'other'; room?:string|null; groupLabel?:string|null; subjectId?:string|null }
export async function createTimetableEntry(input: TimetableInput) { const userId = await getUserId(); const title = input.title.trim().slice(0,160); if (!title || input.dayOfWeek < 1 || input.dayOfWeek > 7) throw new Error('Invalid class'); return (await db.insert(timetableEntries).values({ id: crypto.randomUUID(), userId, ...input, title, slotCode: input.slotCode ?? null, room: null, groupLabel: input.groupLabel ?? null, subjectId: input.subjectId ?? null }).returning())[0] }
export async function updateTimetableEntry(id:string, input:TimetableInput) { const userId = await getUserId(); return (await db.update(timetableEntries).set({ ...input, title: input.title.trim().slice(0,160), room: null, slotCode: input.slotCode ?? null, groupLabel: input.groupLabel ?? null, subjectId: input.subjectId ?? null }).where(and(eq(timetableEntries.id,id),eq(timetableEntries.userId,userId))).returning())[0] }
export async function deleteTimetableEntry(id:string) { const userId = await getUserId(); await db.delete(timetableEntries).where(and(eq(timetableEntries.id,id),eq(timetableEntries.userId,userId))); return {ok:true} }
export async function createStarterSubjects() { const userId = await getUserId(); const names=['Mathematics-I','Oscillations, Waves and Optics','Engineering Graphics and CAD (EG-CAD)','Basics of Analog and Digital Electronics (BADE)','Computer Programming','Sports']; const existing=await db.select().from(subject).where(eq(subject.userId,userId)); const ids:Record<string,string>={}; for (const name of names) { const found=existing.find(s=>s.name.toLowerCase()===name.toLowerCase()); ids[name]=found?.id ?? (await db.insert(subject).values({id:crypto.randomUUID(),userId,name}).returning())[0].id } return ids }
export async function loadStarterTimetable(mapping: Record<string,string|null>) { const userId=await getUserId(); await db.delete(timetableEntries).where(eq(timetableEntries.userId,userId)); const rows:[number,string,string,string,string,'lecture'|'lab'|'tutorial'|'break'|'other',string|null][]=[
[1,'10:00','12:00','Sports','', 'other',null],[1,'12:00','13:00','Oscillations, Waves and Optics','', 'lecture',null],[1,'13:00','14:00','Computer Programming','', 'lecture',null],[1,'14:00','15:00','Lunch','', 'break',null],[1,'17:00','18:00','Computer Programming Lab','', 'lab','G2'],
[2,'10:00','12:00','Sports','', 'other',null],[2,'12:00','13:00','Mathematics-I','', 'lecture',null],[2,'13:00','14:00','Engineering Graphics and CAD (EG-CAD)','', 'lecture',null],[2,'14:00','15:00','Basics of Analog and Digital Electronics (BADE)','', 'lecture',null],[2,'16:00','17:00','Computer Programming','', 'lecture',null],
[3,'11:00','12:00','Oscillations, Waves and Optics Lab','', 'lab','G2'],[3,'12:00','13:00','Oscillations, Waves and Optics','', 'lecture',null],[3,'16:00','17:00','Engineering Graphics and CAD Lab','', 'lab','G2'],
[4,'13:00','14:00','Basics of Analog and Digital Electronics Lab','', 'lab','G2'],[4,'14:00','15:00','Basics of Analog and Digital Electronics (BADE)','', 'lecture',null],[4,'15:00','16:00','Computer Programming','', 'lecture',null],[4,'16:00','17:00','Engineering Graphics and CAD (EG-CAD)','', 'lecture',null],[4,'17:00','18:00','Mathematics-I','', 'lecture',null],
[5,'11:00','12:00','Mathematics-I Tutorial','', 'tutorial','G2'],[5,'12:00','13:00','Oscillations, Waves and Optics','', 'lecture',null],[5,'13:00','14:00','Basics of Analog and Digital Electronics (BADE)','', 'lecture',null],[5,'14:00','15:00','Mathematics-I','', 'lecture',null],[5,'15:00','16:00','Engineering Graphics and CAD (EG-CAD)','', 'lecture',null]];
for (const [dayOfWeek,startTime,endTime,title,slotCode,kind,groupLabel] of rows) await db.insert(timetableEntries).values({id:crypto.randomUUID(),userId,dayOfWeek,startTime,endTime,title,slotCode,kind,room:null,groupLabel,subjectId:mapping[title] ?? null}); return db.select().from(timetableEntries).where(eq(timetableEntries.userId,userId)) }
export async function getSubjectOptions(){ const userId=await getUserId(); return db.select().from(subject).where(eq(subject.userId,userId)) }
