'use server'

import { and, eq } from 'drizzle-orm'
import { headers } from 'next/headers'
import { auth } from '@/lib/auth'
import { db } from '@/lib/db'
import { subject, timetableEntries, userSettings } from '@/lib/db/schema'

async function getUserId() { const session = await auth.api.getSession({ headers: await headers() }); if (!session?.user) throw new Error('Unauthorized'); return session.user.id }
export async function getTimetableData() { const userId = await getUserId(); const [entries, settings] = await Promise.all([db.select().from(timetableEntries).where(eq(timetableEntries.userId, userId)), db.select().from(userSettings).where(eq(userSettings.userId, userId)).limit(1)]); return { entries, labGroup: settings[0]?.labGroup ?? null } }
export async function saveLabGroup(labGroup: 'G1' | 'G2' | null) { const userId = await getUserId(); const existing = await db.select().from(userSettings).where(eq(userSettings.userId, userId)).limit(1); if (existing[0]) return (await db.update(userSettings).set({ labGroup }).where(eq(userSettings.userId, userId)).returning())[0]; return (await db.insert(userSettings).values({ userId, labGroup }).returning())[0] }
export type TimetableInput = { dayOfWeek:number; startTime:string; endTime:string; title:string; slotCode?:string|null; kind:'lecture'|'lab'|'tutorial'|'break'|'other'; room?:string|null; groupLabel?:string|null; subjectId?:string|null }
export async function createTimetableEntry(input: TimetableInput) { const userId = await getUserId(); const title = input.title.trim().slice(0,160); if (!title || input.dayOfWeek < 1 || input.dayOfWeek > 7) throw new Error('Invalid class'); return (await db.insert(timetableEntries).values({ id: crypto.randomUUID(), userId, ...input, title, slotCode: input.slotCode ?? null, room: input.room ?? null, groupLabel: input.groupLabel ?? null, subjectId: input.subjectId ?? null }).returning())[0] }
export async function updateTimetableEntry(id:string, input:TimetableInput) { const userId = await getUserId(); return (await db.update(timetableEntries).set({ ...input, title: input.title.trim().slice(0,160), slotCode: input.slotCode ?? null, room: input.room ?? null, groupLabel: input.groupLabel ?? null, subjectId: input.subjectId ?? null }).where(and(eq(timetableEntries.id,id),eq(timetableEntries.userId,userId))).returning())[0] }
export async function deleteTimetableEntry(id:string) { const userId = await getUserId(); await db.delete(timetableEntries).where(and(eq(timetableEntries.id,id),eq(timetableEntries.userId,userId))); return {ok:true} }
export async function createStarterSubjects() { const userId = await getUserId(); const names=['Mathematics-I','Computer Programming','Oscillations Waves and Optics','Engineering Graphics and CAD','Basics of Analog and Digital Electronics']; const existing=await db.select().from(subject).where(eq(subject.userId,userId)); const ids:Record<string,string>={}; for (const name of names) { const found=existing.find(s=>s.name.toLowerCase()===name.toLowerCase()); ids[name]=found?.id ?? (await db.insert(subject).values({id:crypto.randomUUID(),userId,name}).returning())[0].id } return ids }
export async function loadStarterTimetable(mapping: Record<string,string|null>) { const userId=await getUserId(); const rows=[['10:00','12:00','VA Batch-2','', 'other','',''],['12:00','13:00','E6 · Oscillations Waves and Optics','E6','lecture','205',''],['13:00','14:00','E2 · Computer Programming','E2','lecture','205',''],['14:00','15:00','Lunch','','break','',''],['16:00','18:00','P4 · Engineering Graphics and CAD Lab','P4','lab','','G1'],['16:00','18:00','P2 · Computer Programming Lab','P2','lab','','G2']]; const days=[rows, [['10:00','12:00','VA Batch-2','','other','',''],['12:00','13:00','E3 · Mathematics-I','E3','lecture','205',''],['13:00','14:00','E4 · Engineering Graphics and CAD','E4','lecture','205',''],['14:00','15:00','E5 · Basics of Analog and Digital Electronics','E5','lecture','205',''],['15:00','17:00','P5 · Basics of Analog and Digital Electronics Lab','P5','lab','','G1'],['17:00','18:00','E2 · Computer Programming','E2','lecture','205','']], [['10:00','12:00','P2 · Computer Programming Lab','P2','lab','','G1'],['10:00','12:00','P6 · Oscillations Waves and Optics Lab','P6','lab','','G2'],['12:00','13:00','E6 · Oscillations Waves and Optics','E6','lecture','205',''],['16:00','18:00','P4 · Engineering Graphics and CAD Lab','P4','lab','','G2']], [['12:00','14:00','P6 · Oscillations Waves and Optics Lab','P6','lab','','G1'],['12:00','14:00','P5 · Basics of Analog and Digital Electronics Lab','P5','lab','','G2'],['14:00','15:00','E5 · Basics of Analog and Digital Electronics','E5','lecture','205',''],['15:00','16:00','E2 · Computer Programming','E2','lecture','205',''],['16:00','17:00','E4 · Engineering Graphics and CAD','E4','lecture','205',''],['17:00','18:00','E3 · Mathematics-I','E3','lecture','205','']], [['10:00','11:00','T3 · Mathematics-I Tutorial','T3','tutorial','','G1'],['11:00','12:00','T3 · Mathematics-I Tutorial','T3','tutorial','','G2'],['12:00','13:00','E6 · Oscillations Waves and Optics','E6','lecture','205',''],['13:00','14:00','E5 · Basics of Analog and Digital Electronics','E5','lecture','205',''],['14:00','15:00','E3 · Mathematics-I','E3','lecture','205',''],['15:00','16:00','E4 · Engineering Graphics and CAD','E4','lecture','205','']]]; const values=days.flatMap((day,di)=>day.map(([start,end,title,slotCode,kind,room,groupLabel])=>({id:crypto.randomUUID(),userId,dayOfWeek:di+1,startTime:start,endTime:end,title,slotCode:slotCode||null,kind:kind as TimetableInput['kind'],room:room||null,groupLabel:groupLabel||null,subjectId: mapping[title.replace(/^\w+ · /,'').replace(' Lab','').replace(' Tutorial','')] ?? null}))); return db.insert(timetableEntries).values(values).returning() }
export async function getSubjectOptions(){ const userId=await getUserId(); return db.select().from(subject).where(eq(subject.userId,userId)) }

